language: c
compiler: clang
before_install:
    - wget https://dist.libuv.org/dist/v1.22.0/libuv-v1.22.0.tar.gz
    - tar -xzf libuv*.tar.gz
    - pushd libuv*
    - sh autogen.sh
    - ./configure
    - make
    - sudo make install
    - popd
script: make
