#define OCEAN                   0   
#define PLAINS                  1   
#define DESERT                  2   
#define EXTREME_HILLS           3   
#define FOREST                  4   
#define TAIGA                   5   
#define SWAMPLAND               6   
#define RIVER                   7   
#define NETHER                  8   
#define END                     9   
#define FROZEN_OCEAN            10  
#define FROZEN_RIVER            11  
#define ICE_PLAINS              12  
#define ICE_MOUNTAINS           13  
#define MUSHROOM_ISLAND         14  
#define MUSHROOM_ISLAND_SHORE   15  
#define BEACH                   16  
#define DESERT_HILLS            17  
#define FOREST_HILLS            18  
#define TAIGA_HILLS             19  
#define EXTREME_HILLS_EDGE      20  
#define JUNGLE                  21  
#define JUNGLE_HILLS            22  
#define JUNGLE_EDGE             23  
#define DEEP_OCEAN              24  
#define STONE_BEACH             25  
#define COLD_BEACH              26  
#define BIRCH_FOREST            27  
#define BIRCH_FOREST_HILLS      28  
#define ROOFED_FOREST           29  
#define COLD_TAIGA              30  
#define COLD_TAIGA_HILLS        31  
#define MEGA_TAIGA              32  
#define MEGA_TAIGA_HILLS        33  
#define EXTREME_HILLS+          34  
#define SAVANNA                 35  
#define SAVANNA_PLATEAU         36  
#define MESA                    37  
#define MESA_PLATEAU_F          38  
#define MESA_PLATEAU            39  
#define SUNFLOWER_PLAINS        129 
#define DESERT_M                130 
#define EXTREME_HILLS_M         131 
#define FLOWER_FOREST           132 
#define TAIGA_M                 133 
#define SWAMPLAND_M             134 
#define ICE_PLAINS_SPIKES       140 
#define JUNGLE_M                149 
#define JUNGLEEDGE_M            151 
#define BIRCH_FOREST_M          155 
#define BIRCH_FOREST_HILLS_M    156 
#define ROOFED_FOREST_M         157 
#define COLD_TAIGA_M            158 
#define MEGA_SPRUCE_TAIGA       160 
#define MEGA_SPRUCE_TAIGA_HILLS 161 
#define EXTREME_HILLS+ M        162 
#define SAVANNA_M               163 
#define SAVANNA_PLATEAU_M       164 
#define MESA (BRYCE)            165 
#define MESA_PLATEAU_F M        166 
#define MESA_PLATEAU_M          167 
